apiVersion: batch/v1
kind: Job
metadata:
  name: deploy
spec:
  template:
    metadata:
      labels:
        quest: deploy
    spec:
      containers:
      - name: deploy-ctn
        image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/nba-quest-deploy:0.5.0
        command: ["/bin/sh", "-c", "/deploy/deploy.sh"]
        envFrom:
        - secretRef:
            name: aws-credentials
        - secretRef:
            name: meta-data
        - configMapRef:
            name: deploy-config
      restartPolicy: Never
  backoffLimit: 0

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: deploy
# spec:
#   template:
#     metadata:
#       labels:
#         app: quest
#     spec:
#       containers:
#       - name: quest
#         image: perl:5.34.0
#         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
#       restartPolicy: Never
#   backoffLimit: 4
