apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: public.ecr.aws/s2t1t5c1/seomj:6.0
        command: ["/bin/sh", "-c", "/deploy/deploy_test.sh"]
        envFrom:
        - secretRef:
            name: aws-credentials
        - configMapRef:
            name: test-deploy-config
      restartPolicy: Never
  backoffLimit: 4