apiVersion: batch/v1
kind: Job
metadata:
  name: deploy
spec:
  template:
    spec:
      containers:
      - name: deploy-ctn
        image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/nba-quest-deploy:0.2.1
        command: ["/bin/sh", "-c", "/deploy/deploy_test.sh"]
        envFrom:
        - secretRef:
            name: aws-credentials
        - secretRef:
            name: meta-data
        - configMapRef:
            name: deploy-configmap
      restartPolicy: Never