apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - name: tcp
        containerPort: 80
    envFrom:
    - secretRef:
        name: aws-credentials
    - secretRef:
        name: meta-data
    - configMapRef:
        name: provision-config
    - configMapRef:
        name: deploy-config

# apiVersion: v1
# kind: Pod
# metadata:
#   name: provision
# spec:
#   containers:
#   - name: provision-ctn
#     image: nginx:latest
#     envFrom:
#     - secretRef:
#         name: aws-credentials
#     - secretRef:
#         name: meta-data
#     - configMapRef:
#         name: provision-config