apiVersion: v1
kind: Pod
metadata:
  name: provision
spec:
  containers:
  - name: provision-ctn
    image: nginx:latest
    envFrom:
    - secretRef:
        name: aws-credentials
    - secretRef:
        name: meta-data
    - configMapRef:
        name: provision-config