apiVersion: v1
kind: Pod
metadata:
  name: full-eks
  namespace: default
spec:
  containers:
  - name: full-eks-ctn
    image: kimdoran/ubuntu-terraform:6.0
    command: ["/bin/sh", "-c"]
    args: ["/provision/1013test.sh"]
    envFrom:
    - secretRef:
        name: aws-credentials
  restartPolicy: Never