apiVersion: v1
kind: Pod
metadata:
  name: provision
spec:
  containers:
  - name: provision-ctn
    image: kimdoran/ubuntu-terraform:6.0
    command: ["/bin/sh", "-c"]
    args: ["/provision/1013test.sh"]
    envFrom:
    - secretRef:
        name: aws-credentials
  restartPolicy: Never