apiVersion: v1
kind: Pod
metadata:
   name: provision
   lables:
     quest: provision
spec:
   containers:
   - name: provision-ctn
     image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/nba_full_provision:2.1
     envFrom:
       - configMapRef:
          name: provision-config
       - secretRef:
           name: aws-credentials
       - secretRef:
           name: meta-data
     command : ["/bin/bash", "-c"]
     args: ["/provision/select.sh && tail -f /dev/null"]
   restartPolicy: Never