apiVersion: v1
kind: Pod
metadata:
   name: provision
   lables:
     quest: provision
spec:
   containers:
   - name: provision-ctn
     image: 622164100401.dkr.ecr.ap-northeast-1.amazonaws.com/nba_full_provision:2.2.2
     envFrom:
       - configMapRef:
          name: provision-config
       - secretRef:
           name: aws-credentials
       - secretRef:
           name: meta-data
     command : ["/bin/bash", "-c"]
     args: ["/provision/rev.03_full_pro.sh && tail -f /dev/null"]
   restartPolicy: Never
        
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
# spec:
#   containers:
#   - name: nginx-container
#     image: nginx:latest
#     ports:
#       - name: tcp
#         containerPort: 80
#     envFrom:
#     - secretRef:
#         name: aws-credentials
#     - secretRef:
#         name: meta-data
#     - configMapRef:
#         name: provision-config
#     - configMapRef:
#         name: deploy-config